### ISSUE TITLE
Credit Risk Scorecard Modeling example

### ISSUE THREAD

**Issue by xiaodaigh** [statcompute/yager#1]
I am a scoreacard expert. Can I see a simple credit scoring example? Using German Credit data?

**Comment by statcompute** [comment]
This is your request instead of being the package issue. 
Should you have any request or question, please contact me directly instead of opening an issue. 
Thanks.

**Comment by xiaodaigh** [comment]
Firstly, there is no instruction on where to ask a question.

Just keen to see how it works so I can assess it that's all

See http://skyscorer.com/demo for a complete credit scoring solution in R with Shiny

Also, think of this as a request is fine. I think it will help you spread the word on the package if that's indeed something you want.

Some people allow asking questions on GitHub, as there is a questions label. I respect that you don't want to use Github for questions. But having questions on GitHub issues makes thing more googlable than if you answer them by email, and will help people who come across in general.
