### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by VladPerervenko** [statcompute/yager#2]
The same mistake. What's wrong?
`> install.packages("C:/Users/User/Downloads/yager_0.1.0.tar.gz", repos = NULL, type = "source")
Installing package into ‘C:/Users/User/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
Ошибка в getOctD(x, offset, len) :invalid octal digit
Warning in install.packages :
  installation of package ‘C:/Users/User/Downloads/yager_0.1.0.tar.gz’ had non-zero exit status`

**Comment by statcompute** [comment]
I just tested and installed it on win10 pro without any issue. Could you please check if the file you downloaded is a valid tarball?

**Comment by statcompute** [comment]
Vlad, did you have chance to test the tarball again? If there is no further problem, I am going to close the issue. Thanks.

**Comment by VladPerervenko** [comment]
Hi,
Yes, everything is fine. It was installed without problems. I will test
later. Now is the holidays. Good luck

вс, 5 янв. 2020 г. в 20:09, WenSui Liu <notifications@github.com>:

**Comment by statcompute** [comment]
Thanks for the reply, Vlad. I will close the issue now.
